-- require("fended.telescope-config")
require("fended.lsp-config")
require("fended.compe-config")
-- require("fended.symbols-outline-config")
-- require("fended.treesitter-config")
-- require("fended.presence-config")
